
markdown: kramdown

highlighter: rouge
url: https://wangliyao518.github.io
exclude: ['README.md']


# collection and their defaults

collections:
  front-pages:
    output: true
  modules-intro:
    output: true
  loop-description:
    output: false
  tutorials:
    output: true
    permalink: /:collection/:path/
  table-contents:
    output: true
    permalink: /tutorials/:path/


defaults:
  - scope:
      path: "_front-pages"
    values:
      layout: front-page
      enable_ads: true

  - scope:
      path: "_modules-intro"
    values:
      layout: front-page

  - scope:
      path: "_table-contents"
    values:
      layout: table-of-contents

  - scope:
      path: "_tutorials"
    values:
      layout: tutorial-post
      editor: leo
      author: leo
      author-link: "#"
      enable_ads: true
      published: true  #TOD: change back to true

  # module descriptions
  - scope:
      path: "_loop-description/python-3"
    values:
      module: python-3
  - scope:
      path: "_loop-description/robot-basic"
    values:
      module: robot-basic
  - scope:
      path: "_loop-description/home"
    values:
      module: home
  - scope:
      path: "_loop-description/others"
    values:
      module: others



  # tutorial default


  - scope:
      path: "_tutorials/python-3/multiprocessing"
    values:
      series: 多进程 Multiprocessing
      tut-permalink: /tutorials/python-3/multiprocessing/
      category: multiprocessing
      keywords: python, 基础, 多进程, multiprocessing
      thumbnail: /static/img/course_cover/multiprocessing.jpg

  - scope:
      path: "_tutorials/python-3/threading"
    values:
      series: 多线程 Threading
      tut-permalink: /tutorials/python-3/threading/
      category: threading
      keywords: python, 基础, 多线程, threading
      thumbnail: /static/img/course_cover/threading.jpg


  - scope:
      path: "_tutorials/python-3/tkinter"
    values:
      series: 窗口 Tkinter
      tut-permalink: /tutorials/python-3/tkinter/
      category: tkinter
      keywords: python, 基础, GUI, 窗口, tkinter, tk
      thumbnail: /static/img/course_cover/tkinter.jpg

  - scope:
      path: "_tutorials/python-3/basic"
    values:
      series: Python 基础
      tut-permalink: /tutorials/python-3/basic/
      category: basic
      keywords: python, 基础
      thumbnail: /static/img/course_cover/python_basic.jpg

  - scope:
      path: "_tutorials/robot-basic/basic"
    values:
      series: robot 基础
      tut-permalink: /tutorials/robot-basic/basic/
      category: robot-basic
      keywords: robot, 基础
      thumbnail: /static/img/course_cover/robot_basic.jpg

  - scope:
      path: "_tutorials/robot-basic/arch_and_tools"
    values:
      series: robot architecture and tools
      tut-permalink: /tutorials/robot-basic/arch_and_tools/
      category: robot-arch-and-tools
      keywords: arch tools
      thumbnail: /static/img/course_cover/tkinter.jpg

  - scope:
      path: "_tutorials/robot-basic/robot_data"
    values:
      series: robot keyword series
      tut-permalink: /tutorials/robot-basic/robot_data/
      category: robot_data
      keywords: robot data, test case
      thumbnail: /static/img/course_cover/tkinter.jpg


  - scope:
      path: "_tutorials/others/linux-basic"
    values:
      series: Linux 简易教学
      tut-permalink: /tutorials/others/linux-basic/
      category: linux-basic
      keywords: linux, 基础
      thumbnail: /static/img/course_cover/ML_intro.png

  - scope:
      path: "_tutorials/others/git"
    values:
      series: Git 版本管理
      tut-permalink: /tutorials/others/git/
      category: git
      keywords: 其他, git, VCS
      thumbnail: /static/img/course_cover/git.jpg
      published: true